apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: joplin
deploy:
  kubectl:
    manifests:
      - ./k8s/postgres-secret.yaml
      - ./k8s/postgres-deployment.yaml
      - ./k8s/joplin-server-deployment.yaml

