apiVersion: v1
kind: Service
metadata:
  name: log-parser
spec:
  type: LoadBalancer 
  selector:
    app: log-parser
  ports:
    - port: 5009        # The port the service will expose
      targetPort: 5009   # The port on the container
      protocol: TCP
