apiVersion: v1
kind: Service
metadata:
  name: money-app
spec:
  type: LoadBalancer 
  selector:
    app: money-app
  ports:
    - port: 5022        # The port the service will expose
      targetPort: 5022   # The port on the container
      protocol: TCP
