apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      initContainers:
      - name: install-kubectl
        image: bitnami/kubectl:latest
        command: ['sh', '-c', 'cp /opt/bitnami/kubectl/bin/kubectl /kubectl-dir/kubectl']
        volumeMounts:
        - name: kubectl-bin
          mountPath: /kubectl-dir
          
      containers:
      - name: jenkins
        image: jenkins/jenkins:latest
        ports:
        - containerPort: 8080
        - containerPort: 50000
        securityContext:
          privileged: true
        volumeMounts:
        - name: jenkins-data
          mountPath: /var/jenkins_home
        - name: docker-sock
          mountPath: /var/run/docker.sock
        - name: docker-bin
          mountPath: /usr/local/bin/docker
        - name: kubectl-bin
          mountPath: /usr/local/bin/kubectl
          subPath: kubectl
          
      volumes:
      - name: jenkins-data
        hostPath:
          path: /home/k8server/jenkins
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: docker-bin
        hostPath:
          path: /usr/local/bin/docker
      - name: kubectl-bin
        emptyDir: {}
