apiVersion: v1
kind: PersistentVolume
metadata:
  name: splunk-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/k8s/splunk

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: splunk-pvc
  namespace: splunk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: splunk-pv

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: splunk
  namespace: splunk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: splunk
  template:
    metadata:
      labels:
        app: splunk
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - k8s-worker2
      containers:
        - name: splunk
          image: splunk/splunk:latest # Replace with the stable version as needed
          env:
          - name: SPLUNK_START_ARGS
            value: "--accept-license"
          - name: SPLUNK_PASSWORD
            value: P@ssw0rd
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: splunk-storage
              mountPath: /opt/splunk/etc
      volumes:
        - name: splunk-storage
          persistentVolumeClaim:
            claimName: splunk-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: splunk-service
  namespace: splunk
spec:
  type: LoadBalancer
  ports:
    - port: 8000
  selector:
    app: splunk
