apiVersion: v1
kind: Namespace
metadata:
  name: ghost-namespace
---  
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ghost-pv
  namespace: ghost-namespace  # Corrected here
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/home/k8s/ghost-pv"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-pvc
  namespace: ghost-namespace  # Corrected here
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deployment
  namespace: ghost-namespace  # Corrected here
  labels:
    app: ghost
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost:3-alpine
        ports:
        - containerPort: 2368
        env:
        - name: url
          value: http://localhost:2368
        volumeMounts:
        - name: ghost-storage
          mountPath: /var/lib/ghost/content
      volumes:
      - name: ghost-storage
        persistentVolumeClaim:
          claimName: ghost-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ghost-service
  namespace: ghost-namespace  # Corrected here
spec:
  selector:
    app: ghost
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 2368
  type: LoadBalancer
