apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: LogParser
build:
  local:
    push: true  # Push to your private Docker registry
  artifacts:
    - image: registry.helixx.cloud/log-parser  # Use your private registry URL
      context: .
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - k8s/deployment.yaml
      - k8s/service.yaml
      - k8s/hpa.yaml
