apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ hpa_name }}  # Name of the HPA
  namespace: {{ namespace }}  # Namespace of the HPA
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ deployment_name }}  # Must match the deployment name
  minReplicas: {{ min_replicas }}  # Minimum number of replicas
  maxReplicas: {{ max_replicas }}  # Maximum number of replicas
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ target_cpu_utilization }}  # Target CPU utilization percentage
