apiVersion: apps/v1
kind: Deployment
metadata:
  name: freshrss
  namespace: freshrss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freshrss
  template:
    metadata:
      labels:
        app: freshrss
    spec:
      containers:
        - name: freshrss
          image: freshrss/freshrss:latest
          ports:
            - containerPort: 80
          env:
            - name: TZ                    # Add this environment variable
              value: "America/New_York"   # Set timezone to New York
          volumeMounts:
            - name: freshrss-data
              mountPath: /var/www/FreshRSS/data  # Default data directory for FreshRSS
      volumes:
        - name: freshrss-data
          persistentVolumeClaim:
            claimName: freshrss-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: freshrss-service
  namespace: freshrss
spec:
  type: LoadBalancer
  selector:
    app: freshrss
  ports:
    - port: 80
      targetPort: 80
  loadBalancerIP: 192.168.1.123  # Assigning the specific IP address
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: freshrss-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/home/$USER/freshRSS_K8s"  # Mounting to the specified path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-pvc
  namespace: freshrss
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: freshrss-pv
  storageClassName: ""  # Disable dynamic provisioning
